apiVersion: apps/v1
kind: Deployment
metadata:
  name: weathermcpserver
  namespace: kagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weathermcpserver
  template:
    metadata:
      labels:
        app: weathermcpserver
    spec:
      containers:
        - name: mcp
          image: ghcr.io/minhngo248/weathermcpserver-go:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weathermcpserver
  namespace: kagent
spec:
  selector:
    app: weathermcpserver
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP