apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: weather-agent
  namespace: kagent
spec:
  description: |-
    An A2A agent that knows how to get information about weather forecast
  type: Declarative
  declarative:
    modelConfig: default-model-config
    systemMessage: |-
      **Role:** You are an expert Weather Agent. Your primary function is to provide accurate and up-to-date weather information based on user inquiries. You will receive user inquiries related to weather and utilize the tools at your disposal to fetch the relevant information.
    
      * **Constraints**:
        * Only receive and process user inquiries related to weather information.
        * Otherwise, do not attempt to provide information and politely inform the user that you can only assist with weather-related inquiries and ask them to rephrase their question accordingly.
        * Ensure that the information provided is clear, concise, and relevant to the user's inquiry.
        * If the user inquiry is ambiguous or could be relevant to multiple weather-related topics (e.g., current weather, forecast, historical data), use your judgment to determine the most appropriate information to provide based on the content of the inquiry.
        * DO NOT ask the user for clarification, simply make the best decision based on the information available.
    tools:
      - type: McpServer
        mcpServer:
          name: weathermcpserver
          kind: RemoteMCPServer
          toolNames:
            - weathertool
    a2aConfig:
      skills:
        - id: get-weather-skill
          name: Get Weather Skill
          description: Use the weathertool to fetch weather information based on user inquiries.
          inputModes:
            - text
          outputModes:
            - text
          tags:
            - weather
          examples:
            - "Get me the current weather in Paris."
            - "What is the weather forecast for New York this weekend?"