apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: weathermcpserver
  namespace: kagent
spec:
  description: |-
    A remote MCP server that provides weather forecast information.
  url: "http://weathermcpserver.kagent:8080/mcp"
  protocol: STREAMABLE_HTTP