server.port=8083
spring.application.name=orchestrator

spring.ai.retry.max-attempts=1

## OpenAI SDK
spring.ai.openai-sdk.api-key=${OPENAI_API_KEY}
spring.ai.openai-sdk.chat.options.model=${OPENAI_MODEL:gpt-5-mini-2025-08-07}
spring.ai.openai-sdk.chat.options.temperature=1.0

spring.ai.chat.memory.repository.jdbc.initialize-schema=never

## Remote A2A agents to connect to
remote.agents.urls=${TOURIST_AGENT_URL:http://localhost:8081},${WEATHER_AGENT_URL:http://localhost:8082}

## Configure DataSource and Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.xml
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

## Actuator configuration
management.endpoints.web.exposure.include=mappings,health,info