server.port=8083
spring.application.name=orchestrator

spring.ai.retry.max-attempts=1
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.options.model=${OPENAI_MODEL:gpt-4o-mini}
spring.ai.openai.options.temperature=0.7
spring.ai.openai.options.max-tokens=1000
spring.ai.chat.memory.repository.jdbc.initialize-schema=never

## Remote A2A agents to connect to
remote.agents.urls=${TOURIST_AGENT_URL:http://localhost:8081},${WEATHER_AGENT_URL:http://localhost:8082}

## Configure DataSource and Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.xml
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

## Actuator configuration
management.endpoints.web.exposure.include=mappings,health,info