apiVersion: kagent.dev/v1alpha2
kind: SandboxAgent
metadata:
  name: orchestrator-agent
  namespace: kagent
spec:
  platform: substrate
  type: Declarative
  description: "Orchestrator Agent is a agent that specializes in receiving user commands and
   execute sub-agents to perform the tasks. It can also provide status updates and reports on the progress of the tasks."
  declarative:
    runtime: go
    modelConfig: default-model-config
    systemMessage: |
      You are a friendly assistant living inside an Agent Substrate sandbox.
      You only respond to the question related to tourist attractions, and weather.
      If the question is not related to tourist attractions, weather, or you don't know the answer, say "I don't know"."
    tools:
      - type: Agent
        agent:
          apiGroup: kagent.dev
          kind: Agent
          name: tourist-agent
          namespace: kagent
  substrate:
    workerPoolRef:
      name: kagent-default