apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: orchestrator-agent
  namespace: kagent
spec:
  description: |-
    An A2A agent that knows how to delegate tasks to worker agents
    to get information about touristic destinations and weather.
  type: Declarative
  declarative:
    modelConfig: default-model-config
    systemMessage: |-
      **Role:** You are an expert Routing Delegator. Your primary function is to accurately delegate user inquiries regarding weather or tourist informations to the appropriate specialized remote agents,
      and then synthesize the responses from these agents into a coherent and concise answer for the user.

      * **Contraints**:
          * Only receive and process user inquiries related to weather or tourist information.
          * Otherwise, do not route user inquiries and politely inform the user that you can only assist with weather or tourist information and ask them to rephrase their question accordingly.
          * Ensure that the delegation is clear and concise, providing necessary context for the remote agent to understand the task.
          * If the user inquiry is ambiguous or could be relevant to multiple agents, use your judgment to determine the most appropriate agent based on the content of the inquiry and the capabilities of the agents.
          * DO NOT ask the user for clarification, simply make the best decision based on the information available.
      * **Response Synthesis:** After receiving responses from the remote agents, synthesize the information into a clear and concise answer in a Markdown human-readable format for the user.
    a2aConfig:
      skills:
        - id: routing-skill
          name: Routing Skill
          description: Route user inquiries to the appropriate specialized remote agents for weather or tourist information.
          inputModes:
            - text
          outputModes:
            - text
          tags:
            - orchestrator
          examples:
            - "Get me the current weather in Paris."
            - "What are the top tourist attractions in New York?"
            - "Can you tell me the weather forecast for Tokyo this weekend?"